name: Collect ESP32 state

on:
  schedule:
    - cron: "*/10 * * * *"   # ogni 10 minuti
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: collect-esp32
  cancel-in-progress: false

env:
  BASE_URL: "http://79.21.55.245:1234"   # eventualmente sostituisci con il tuo dominio/DDNS

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Prepare folders and CSV header
        run: |
          mkdir -p states/raw docs
          csv="states/metrics.csv"
          if [ ! -s "$csv" ]; then
            echo "timestamp,soil1,soil2,sens_suolo_anal1,sens_suolo_anal2,t_air_ds,t_soil_ds,bme_t,bme_rh,bme_p,bme_iaq,bme_static_iaq,bme_co2eq,bme_voc,bme_gas_pct,bme_gas_raw,vbat,vpv,ppv,flow_lph,flow_total,valve1,valve2,rtc_epoch_esp32" > "$csv"
          fi

      - name: Fetch /api/state and append row
        run: |
          set -euo pipefail
          ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          curl -fsSL "$BASE_URL/api/state" -o "states/raw/$ts.json"

          jq -r --arg ts "$ts" '
            [
              $ts,
              (.soil1 // 0),
              (.soil2 // 0),
              (.sens_suolo_anal1 // 0),
              (.sens_suolo_anal2 // 0),
              (.t_air_ds // null),
              (.t_soil_ds // null),
              (.bme_t // null),
              (.bme_rh // null),
              (.bme_p // null),
              (.bme_iaq // null),
              (.bme_static_iaq // null),
              (.bme_co2eq // null),
              (.bme_voc // null),
              (.bme_gas_pct // null),
              (.bme_gas_raw // null),
              (.vbat // null),
              (.vpv // null),
              (.ppv // null),
              (.flow_lph // null),
              (.flow_total // null),
              (.valve1 // null),
              (.valve2 // null),
              (.rtc_epoch_esp32 // null)
            ] | @csv
          ' "states/raw/$ts.json" >> states/metrics.csv

          cp states/metrics.csv docs/metrics.csv
          echo "CSV header attuale:"
          head -1 docs/metrics.csv || true

      - name: Commit & push
        run: |
          if git status --porcelain | grep -q .; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add states docs
            git commit -m "update metrics ($(date -u +"%Y-%m-%dT%H:%M:%SZ"))"
            git push
          else
            echo "No changes"
          fi
